training_pipline_config:
  pipline_name: project_name
  artifact_dir: artifact

data_ingestion_config:
  dataset_download_url: 
  raw_data_dir: raw_data
  tgz_download_dir: tgz_data
  ingested_dir: ingested_data
  ingested_train_dir: train
  ingested_test_data: test


data_validation_config:
  schemam_file_name: schema.yaml


data_transformation:
  transformed_dir: transformed_data
  transformed_train_dir: train
  transformed_test_data: test
  preprocessing_dir: preprocessed
  preprocesed_object_file_name: processed.pkl


model_trainer_config:
  trained_model_dir: trained_model
  model_file_name: model.pkl
  base_accuracy: 0.6  


model_evaluation_config:
  model_evaluation_file_name: model_evaluation.yaml


model_pusher_config:
  model_export_dir: saved_models